FuelQuoteApp/Models/Quote/QuoteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FuelQuoteApp.Models.Quote
{
    public class QuoteViewModel
    {
        [Required(ErrorMessage = "Please enter the required quantity of fuel!")]
        public int GallonsRequested { get; set; }

        [ReadOnly(true)]
        public string DeliveryAddress { get; set; }

        [Required(ErrorMessage = "Please enter the date!")]
        [DataType(DataType.Date)]
        public DateTime DateRequested { get; set; }

        [ReadOnly(true)]
        public float PricePerGallon { get; set; }

        [ReadOnly(true)]
        public float TotalAmount { get; set; }
    }
}

FuelQuoteApp/Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FuelQuoteApp.Models.Quote;
using Microsoft.AspNetCore.Mvc;

namespace FuelQuoteApp.Controllers
{
    public class QuoteController : Controller
    {
        [HttpGet]
        public IActionResult GetQuote()
        {
            QuoteViewModel quote = new QuoteViewModel();
            quote.DeliveryAddress = "4045 Linkwood Drive";
            quote.PricePerGallon = 100;
            quote.TotalAmount = 9999;
            return View(quote);
        }


        [HttpGet]
        public IActionResult QuoteHistory()
        {
            QuoteViewModel quote = new QuoteViewModel()
            {
                DateRequested = DateTime.Now,
                GallonsRequested=90,
                DeliveryAddress="Linkwood Drive",
                PricePerGallon=2,
                TotalAmount=1500
            };
            List<QuoteViewModel> quotes = new List<QuoteViewModel>();
            quotes.Add(quote);

            return View(quotes);
        }
    }
}

FuelQuoteApp/Views/Quote/GetQuote.cshtml
@model FuelQuoteApp.Models.Quote.QuoteViewModel

@{
    ViewData["Title"] = "GetQuote";
}

<h2>GetQuote</h2>

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Here is your Quotaition
            </h3>
        </div>
        <div class="panel-body">
            <form role="form" asp-action="GetQuote" asp-controller="Quote" method="post">
                <div class="form-group">
                    <input asp-for="GallonsRequested" class="form-control input-sm" placeholder="Gallons Requested">
                    <span asp-validation-for="GallonsRequested" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="DeliveryAddress" class="form-control input-sm" readonly>
                </div>
                <div class="form-group">
                    <input asp-for="DateRequested" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                    <span asp-validation-for="DateRequested" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="PricePerGallon" class="form-control input-sm" readonly>
                </div>
                <div class="form-group">
                    <input asp-for="TotalAmount" class="form-control input-sm" readonly>
                </div>
                <div class="row">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <input type="submit" value="Get Price" class="btn btn-info btn-block">
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <input type="button" value="Update" class="btn btn-info btn-block">
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

FuelQuoteApp/Views/Quote/QuoteHistory.cshtml
@model IEnumerable<FuelQuoteApp.Models.Quote.QuoteViewModel>

@{
    ViewData["Title"] = "QuoteHistory";
}

<h1>QuoteHistory</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GallonsRequested)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateRequested)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePerGallon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GallonsRequested)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRequested)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerGallon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>